version: '3.8'

services:
  groupx_web:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - group2_db
    volumes:
      - ./src:/var/www/html

  group2_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: group2_shareride_db
      MYSQL_USER: root
      MYSQL_PASSWORD: ""
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  groupx_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: group2_db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8081:80"
    depends_on:
      - group2_db

volumes:
  db_data:
